apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-pipeline-example
  labels:
    app: rails-pipeline-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-pipeline-example
  template:
    metadata:
      labels:
        app: rails-pipeline-example
    spec:
      containers:
      - name: rails-pipeline-example
        image: ghcr.io/davidleechen/rails-pipeline-example:0.0.12
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "production"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: rails-pipeline-example-secret-key-base
---
apiVersion: v1
kind: Service
metadata:
  name: rails-pipeline-example-service
spec:
  selector:
    app: rails-pipeline-example
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rails-pipeline-example-ingress
spec:
  rules:
  - host: rpe.chenware.com
    http:
      paths:
      - backend:
          service:
            name: rails-pipeline-example-service
            port:
              number: 3000
        path: /
        pathType: Prefix
